name: CI

on:
  pull_request:
    branches: [ "master" ]
    
    # Allows for running this workflow manually from the Actions tab
    workflow_dispatch:

jobs:
  dependency-review:
    name: Dependency Review
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
        
      - name: Dependency review
        uses: actions/dependency-review-action@v2

  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: dependency-review
    steps:
      - name: Checkout the code
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
    
      - name: Set up JDK 17
        uses: actions/setup-java@a18c333f3f14249953dab3e186e5e21bf3390f1d
        with:
          java-version: '17'
          distribution: 'corretto'
          cache: maven
    
      - name: Build with Maven
        run: ./mvnw -B package

      # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
      - name: Update dependency graph
        uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
      
  test:
    name: Integration Tests
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: build
    steps:
      - name: Checkout the code
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
    
      - name: Set up JDK 17
        uses: actions/setup-java@a18c333f3f14249953dab3e186e5e21bf3390f1d
        with:
          java-version: '17'
          distribution: 'corretto'
          cache: maven
    
      - name: Run integration tests
        run: ./mvnw -B verify -pl tests -Pintegration-tests -Dheadless
